<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../project/Settings.cs" Link="Settings.cs" />
    <Compile Include="../project/JsonFile.cs" Link="JsonFile.cs" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReactiveProperty" Version="9.7.0" />
  </ItemGroup>
</Project>
